name: Build

on: [push, pull_request]

jobs:
  build_linux:
    name: Build on ${{ matrix.image }} (Qt ${{ matrix.qt }})
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        image: [manylinux_2_28]
        qt: [6.4.2]
        arch: [x86_64]
        experimental: [false]
        include:
          - image: manylinux_2_28
            qt: 6.5.3
            arch: x86_64
            experimental: true
    container:
      image: ghcr.io/python-limereport/pyside_builder_${{ matrix.image }}_${{ matrix.arch }}:qt-${{ matrix.qt }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build
        run: ./build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: /output/*
